# Программирование на языке Python 
# Неделя 7. Форматы структурированных данных: HTML и JSON

При сборе данных из интернета нам пригодится навык работы с двумя типами форматами:

### 1.1. HTML

Большинство сайтов в интернете представляют собой **HTML-страницы** (HyperText Markup Language) — документы, предназначенные для визуального отображения в браузере. HTML использует систему тегов для структурирования контента.

HTML ориентирован на **представление** данных, а не на их хранение или обмен между программами.

### 1.2. JSON

Многие сервисы предоставляют доступ к данным через **API** — набор правил и инструкций, которые позволяют одной программе общаться с другой. Наиболее распространённым форматом, с которым мы имеем дело при обращении к сервису через API, является **JSON** (JavaScript Object Notation):

```json
{
  "name": "Анна",
  "age": 25,
  "is_student": true,
  "courses": ["Математика", "Физика"],
  "address": {
    "city": "Москва",
    "street": "ул. Примерная"
  },
  "phone": null
}
```

**Ключевое отличие:** HTML предназначен для отображения информации пользователю, JSON — для передачи данных между программами.

## 2. JSON: теория

**JSON** (*JavaScript Object Notation*) — текстовый формат обмена данными, основанный на подмножестве синтаксиса JavaScript. JSON независим от языка программирования и поддерживается большинством современных языков.

### 2.1. Правила формирования JSON-документа

1. **Объект** — неупорядоченная коллекция пар `ключ: значение`, заключённая в фигурные скобки `{}`. Ключи представляют собой строки в двойных кавычках.
2. **Массив** — упорядоченная коллекция значений, заключённая в квадратные скобки `[]`.
3. **Значения** могут быть следующих типов:
   - число (целое или с плавающей точкой): `42`, `3.14`
   - строка (в двойных кавычках): `"текст"`
   - логическое значение: `true`, `false`
   - `null` — отсутствие значения
   - массив

### 2.2. Соответствие типов Python и JSON

| Python | JSON |
|--------|-------|
| `dict` | объект `{}` |
| `list`, `tuple` | массив `[]` |
| `str` | строка |
| `int`, `float` | число |
| `True` | `true` |
| `False` | `false` |
| `None` | `null` |

**Примечание:** в JSON используются исключительно двойные кавычки `"` для строк и ключей. Одинарные кавычки `'` не являются валидным синтаксисом JSON, что отличает его от синтаксиса словарей Python.

## 3. JSON: практика в Python

Для работы с JSON в Python используется встроенный модуль `json`.

### 3.1. Основные функции модуля `json`

| Функция | Назначение |
|---------|------------|
| `json.loads(s)` | Десериализация **строки** JSON в объект Python |
| `json.load(f)` | Десериализация **файла** JSON в Python |
| `json.dumps(obj)` | Сериализация объекта Python в **строку** JSON |
| `json.dump(obj, f)` | Сериализация объекта Python в JSON |

In [37]:
import json

### 3.2. Десериализация: `json.loads()`

In [38]:
json_string = '{"name": "Анна", "age": 25, "is_student": true, "courses": ["Математика", "Физика"]}'

data = json.loads(json_string)

print(type(data))  
print(data)
print(data['name']) 
print(data['courses'][0])

<class 'dict'>
{'name': 'Анна', 'age': 25, 'is_student': True, 'courses': ['Математика', 'Физика']}
Анна
Математика

### 3.3. Сериализация: `json.dumps()`

In [39]:
# Словарь Python
student = {
    'name': 'Иван',
    'age': 20,
    'is_student': True,
    'grades': [5, 4, 5, 3],
    'address': None
}

json_string = json.dumps(student)
print(type(json_string)) 
print(json_string)

<class 'str'>
{"name": "\u0418\u0432\u0430\u043d", "age": 20, "is_student": true, "grades": [5, 4, 5, 3], "address": null}

### 3.4. Параметры сериализации

| Параметр | Назначение |
|----------|------------|
| `indent` | Задаёт отступ для форматирования вывода (число пробелов) |
| `ensure_ascii` | При `False` отключает экранирование не-ASCII символов (кириллица остаётся читаемой) |
| `sort_keys` | При `True` сортирует ключи объекта по алфавиту |

In [ ]:
print(json.dumps(student))
print()

print(json.dumps(student, indent=2, ensure_ascii=False))

{"name": "\u0418\u0432\u0430\u043d", "age": 20, "is_student": true, "grades": [5, 4, 5, 3], "address": null}

{
  "name": "Иван",
  "age": 20,
  "is_student": true,
  "grades": [
    5,
    4,
    5,
    3
  ],
  "address": null
}

### 3.5. Работа с файлами JSON

#### Запись в JSON: `json.dump()`

In [41]:
data = {
    'name': 'Мария',
    'age': 22,
    'city': 'Санкт-Петербург'
}

with open('student.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

# Проверка
with open('student.json', 'r', encoding='utf-8') as f:
    print(f.read())

{
  "name": "Мария",
  "age": 22,
  "city": "Санкт-Петербург"
}

#### Чтение из файла: `json.load()`

In [42]:
with open('student.json', 'r', encoding='utf-8') as f:
    loaded_data = json.load(f)

print(loaded_data)
print(type(loaded_data))

{'name': 'Мария', 'age': 22, 'city': 'Санкт-Петербург'}
<class 'dict'>

### 3.6. Ограничения сериализации

Не все объекты Python могут быть сериализованы в JSON.

In [43]:
# Кортеж в качестве ключа словаря вызывает ошибку
bad_dict = {('a', 1): 'value'}

try:
    json.dumps(bad_dict)
except TypeError as e:
    print(f'Ошибка: {e}')

# Решение: параметр skipkeys пропускает неподдерживаемые ключи
print(json.dumps(bad_dict, skipkeys=True))  # {}

Ошибка: keys must be str, int, float, bool or None, not tuple
{}

## 4. JSON + pandas

Библиотека pandas предоставляет удобные инструменты для работы с JSON, позволяющие загружать данные в DataFrame.

### 4.1. Чтение JSON-файла: `pd.read_json()`

In [44]:
import pandas as pd

books_data = [
    {"title": "Война и мир", "author": "Лев Толстой", "year": 1869},
    {"title": "Преступление и наказание", "author": "Фёдор Достоевский", "year": 1866},
    {"title": "Мастер и Маргарита", "author": "Михаил Булгаков", "year": 1967}
]

with open('books.json', 'w', encoding='utf-8') as f:
    json.dump(books_data, f, ensure_ascii=False, indent=2)

df = pd.read_json('books.json')
df

                      title             author  year
0               Война и мир        Лев Толстой  1869
1  Преступление и наказание  Фёдор Достоевский  1866
2        Мастер и Маргарита    Михаил Булгаков  1967

### 4.2. Запись DataFrame в JSON: `df.to_json()`

При записи DataFrame в JSON необходимо указать параметр `orient` (от англ. *orientation* — ориентация), который определяет **структуру итогового JSON-документа**.

| Значение `orient` | Структура JSON | Пример |
|-------------------|----------------|--------|
| `'columns'` (по умолчанию) | `{колонка: {индекс: значение}}` | `{"name": {"0": "Анна", "1": "Иван"}}` |
| `'index'` | `{индекс: {колонка: значение}}` | `{"0": {"name": "Анна"}, "1": {"name": "Иван"}}` |
| `'records'` | массив объектов, каждый объект — строка таблицы | `[{"name": "Анна"}, {"name": "Иван"}]` |
| `'values'` | массив массивов без заголовков | `[["Анна", 25], ["Иван", 20]]` |
| `'split'` | отдельные массивы `index`, `columns`, `data` | `{"index": [0,1], "columns": ["name"], "data": [["Анна"],["Иван"]]}` |
| `'table'` | JSON Schema + данные | полная метаданные о таблице |

Для обмена данными чаще всего используется `orient='records'`.

In [45]:
df.to_json('books_output.json', orient='records', force_ascii=False, indent=2)

with open('books_output.json', 'r', encoding='utf-8') as f:
    print(f.read())

[
  {
    "title":"Война и мир",
    "author":"Лев Толстой",
    "year":1869
  },
  {
    "title":"Преступление и наказание",
    "author":"Фёдор Достоевский",
    "year":1866
  },
  {
    "title":"Мастер и Маргарита",
    "author":"Михаил Булгаков",
    "year":1967
  }
]

### 4.3. Вложенные JSON-структуры: `pd.json_normalize()`

При наличии вложенных объектов в JSON, функция `pd.json_normalize()` позволяет преобразовать иерархическую структуру в плоскую таблицу.

In [46]:
# JSON с вложенными объектами
nested_data = [
    {
        "name": "Анна",
        "age": 25,
        "address": {"city": "Москва", "street": "ул. Примерная"}
    },
    {
        "name": "Иван",
        "age": 20,
        "address": {"city": "Санкт-Петербург", "street": "Невский пр."}
    }
]

# Преобразование вложенной структуры в плоскую таблицу
df_nested = pd.json_normalize(nested_data)
df_nested

   name  age     address.city address.street
0  Анна   25           Москва  ул. Примерная
1  Иван   20  Санкт-Петербург    Невский пр.

In [47]:
df_nested.to_json('nested.json', orient='records', force_ascii=False, indent=2)

with open('nested.json', 'r', encoding='utf-8') as f:
    print(f.read())

[
  {
    "name":"Анна",
    "age":25,
    "address.city":"Москва",
    "address.street":"ул. Примерная"
  },
  {
    "name":"Иван",
    "age":20,
    "address.city":"Санкт-Петербург",
    "address.street":"Невский пр."
  }
]

### 4.4. Формат JSONL (JSON Lines)

JSONL — формат, при котором каждая строка файла представляет собой отдельный JSON-объект. Данный формат широко используется для хранения больших объёмов данных.

In [48]:
jsonl_content = '{"word": "кот", "freq": 150}\n{"word": "собака", "freq": 120}\n{"word": "попугай", "freq": 30}\n'

with open('words.jsonl', 'w', encoding='utf-8') as f:
    f.write(jsonl_content)

df_jsonl = pd.read_json('words.jsonl', lines=True)
df_jsonl

      word  freq
0      кот   150
1   собака   120
2  попугай    30

Обычный JSON-массив нельзя прочитать по частям — нужно загрузить весь файл в память и распарсить целиком. Также JSON-массив нельзя дописать объект, не переписав весь файл. JSONL читается построчно:

In [49]:
with open('words.jsonl', 'r', encoding='utf-8') as f:
    for line in f:
        print(json.loads(line))

{'word': 'кот', 'freq': 150}
{'word': 'собака', 'freq': 120}
{'word': 'попугай', 'freq': 30}

## 5. HTML: теория

**HTML** (*HyperText Markup Language*) — стандартный язык разметки для создания веб-страниц. HTML определяет структуру документа с помощью тегов.

### 5.1. Основные правила HTML

1. **Элемент** — основная единица HTML-документа, состоящая из открывающего и закрывающего тега: `<тег>содержимое</тег>`
2. **Атрибуты** — дополнительные параметры элемента: `<тег атрибут="значение">`
3. **Вложенность** — элементы могут содержать дочерние элементы

### 5.2. Структура типичной веб-страницы

Обычный сайт представляет собой HTML-документ со сложной структурой:

```html
<html>
  <body>
    <header>
      <h1>Название сайта</h1>
      <nav>Меню навигации</nav>
    </header>
    <main>
      <article>
        <h2>Заголовок статьи</h2>
        <p>Текст статьи...</p>
        <span class="date">2024-01-15</span>
      </article>
      <article>
        <h2>Другая статья</h2>
        <p>Текст другой статьи...</p>
        <span class="date">2024-01-10</span>
      </article>
    </main>
    <footer>Информация о сайте</footer>
  </body>
</html>
```

## 6. Парсинг HTML

### 6.1. Установка и импорт
**BeautifulSoup** — библиотека Python для парсинга HTML и XML.

In [50]:
# !pip install beautifulsoup4

from bs4 import BeautifulSoup

### 6.2. Создание тестовой HTML-страницы

Создадим HTML-файл, имитирующий обычный сайт с карточками товаров.

In [52]:
html_content = '''<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Магазин книг</title>
</head>
<body>
    <header>
        <h1>Книжный магазин</h1>
        <nav><a href="/">Главная</a> | <a href="/catalog">Каталог</a></nav>
    </header>

    <main>
        <h2>Каталог книг</h2>

        <article class="product">
            <h3 class="title">Война и мир</h3>
            <p class="author">Лев Толстой</p>
            <p class="price">500 руб.</p>
            <span class="year">1869</span>
        </article>

        <article class="product">
            <h3 class="title">Преступление и наказание</h3>
            <p class="author">Фёдор Достоевский</p>
            <p class="price">450 руб.</p>
            <span class="year">1866</span>
        </article>

        <article class="product">
            <h3 class="title">Мастер и Маргарита</h3>
            <p class="author">Михаил Булгаков</p>
            <p class="price">600 руб.</p>
            <span class="year">1967</span>
        </article>

        <article class="product">
            <h3 class="title">Евгений Онегин</h3>
            <p class="author">Александр Пушкин</p>
            <p class="price">350 руб.</p>
            <span class="year">1833</span>
        </article>

        <article class="product">
            <h3 class="title">Собачье сердце</h3>
            <p class="author">Михаил Булгаков</p>
            <p class="price">400 руб.</p>
            <span class="year">1925</span>
        </article>
    </main>

    <footer>
        <p>© 2024 Книжный магазин</p>
    </footer>
</body>
</html>'''

with open('shop.html', 'w', encoding='utf-8') as f:
    f.write(html_content)

### 6.3. Парсинг HTML с помощью BeautifulSoup

In [53]:
# Чтение HTML-файла и создание объекта BeautifulSoup
with open('shop.html', 'r', encoding='utf-8') as f:
    soup = BeautifulSoup(f, 'html.parser')

### 6.4. Извлечение данных из HTML

BeautifulSoup предоставляет несколько методов для поиска элементов:

| Метод | Назначение |
|-------|------------|
| `find(tag, class_)` | Поиск первого элемента с указанным тегом и классом |
| `find_all(tag, class_)` | Поиск всех элементов с указанным тегом и классом |
| `select(css_selector)` | Поиск элементов с помощью CSS-селекторов |
| `element.text` | Извлечение текстового содержимого элемента |

In [55]:
# Поиск всех карточек товаров
products = soup.find_all('article', class_='product')

print(f'Найдено товаров: {len(products)}')
print()

first_product = products[0]
title = first_product.find('h3', class_='title').text
author = first_product.find('p', class_='author').text
price = first_product.find('p', class_='price').text
year = first_product.find('span', class_='year').text

print(f'Название: {title}')
print(f'Автор: {author}')
print(f'Цена: {price}')
print(f'Год: {year}')

Найдено товаров: 5

Название: Война и мир
Автор: Лев Толстой
Цена: 500 руб.
Год: 1869

### 6.5. Сбор данных из всех товаров в список словарей

In [58]:
books = []

for product in products:
    book = {
        'title': product.find('h3', class_='title').text,
        'author': product.find('p', class_='author').text,
        'price': int(product.find('p', class_='price').text.replace(' руб.', '')),
        'year': int(product.find('span', class_='year').text)
    }
    books.append(book)

for book in books:
    print(book)

{'title': 'Война и мир', 'author': 'Лев Толстой', 'price': 500, 'year': 1869}
{'title': 'Преступление и наказание', 'author': 'Фёдор Достоевский', 'price': 450, 'year': 1866}
{'title': 'Мастер и Маргарита', 'author': 'Михаил Булгаков', 'price': 600, 'year': 1967}
{'title': 'Евгений Онегин', 'author': 'Александр Пушкин', 'price': 350, 'year': 1833}
{'title': 'Собачье сердце', 'author': 'Михаил Булгаков', 'price': 400, 'year': 1925}

### 6.6. Создание DataFrame

In [60]:
df_shop = pd.DataFrame(books)
df_shop

                      title             author  price  year
0               Война и мир        Лев Толстой    500  1869
1  Преступление и наказание  Фёдор Достоевский    450  1866
2        Мастер и Маргарита    Михаил Булгаков    600  1967
3            Евгений Онегин   Александр Пушкин    350  1833
4            Собачье сердце    Михаил Булгаков    400  1925

### 6.7. Сохранение результатов в JSON

In [61]:
results = {
    'источник': 'shop.html',
    'всего_товаров': len(df_shop),
    'все_книги': books,
}

with open('shop_analysis.json', 'w', encoding='utf-8') as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

# Проверка
with open('shop_analysis.json', 'r', encoding='utf-8') as f:
    print(f.read())

{
  "источник": "shop.html",
  "всего_товаров": 5,
  "все_книги": [
    {
      "title": "Война и мир",
      "author": "Лев Толстой",
      "price": 500,
      "year": 1869
    },
    {
      "title": "Преступление и наказание",
      "author": "Фёдор Достоевский",
      "price": 450,
      "year": 1866
    },
    {
      "title": "Мастер и Маргарита",
      "author": "Михаил Булгаков",
      "price": 600,
      "year": 1967
    },
    {
      "title": "Евгений Онегин",
      "author": "Александр Пушкин",
      "price": 350,
      "year": 1833
    },
    {
      "title": "Собачье сердце",
      "author": "Михаил Булгаков",
      "price": 400,
      "year": 1925
    }
  ]
}